[env:featheresp32]
platform = espressif32
board = featheresp32
framework = arduino
monitor_speed = 115200

build_flags =
    -DBOARD_HAS_PSRAM
    -DARDUINO_RUNNING_CORE=1
    -DARDUINO_EVENT_RUNNING_CORE=0
    -DCONFIG_ARDUINO_LOOP_STACK_SIZE=8192

lib_deps =
    bblanchon/ArduinoJson @ ^6.21.5
