[env:agente3_featheresp32]
platform = espressif32
board = featheresp32
framework = arduino
monitor_speed = 115200
monitor_dtr = 0
monitor_rts = 0
upload_speed = 921600
; Si tu placa no compila como featheresp32, cambia solo esta línea:
; board = esp32dev
;
; No se requieren librerías externas: el ADS1115 se maneja por I2C a bajo nivel.
